CREATE EXTENSION IF NOT EXISTS citext; 

CREATE TABLE CATEGORIES (
    CODE SERIAL PRIMARY KEY,
    NAME citext UNIQUE,
    TAX NUMERIC(10,2),
    CANDELETE BOOLEAN
);

CREATE TABLE PRODUCTS (
    CODE SERIAL PRIMARY KEY,
    NAME citext UNIQUE,
    AMOUNT INTEGER,
    PRICE NUMERIC(10,2),
    CANDELETE BOOLEAN,
    CATEGORY_CODE INTEGER,
    CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORIES(CODE)
);

CREATE TABLE ORDERS (
    CODE SERIAL PRIMARY KEY,
    TOTAL NUMERIC(10,2),
    TAX NUMERIC(10,2),
    QUANTITY INTEGER,
    PURCHASE_DATE VARCHAR(255) NOT NULL
);

CREATE TABLE ORDER_ITEM(
    CODE SERIAL PRIMARY KEY,
    ORDER_CODE INTEGER,
    PRODUCT_CODE INTEGER,
    AMOUNT INTEGER,
    PRICE NUMERIC(10,2),
    TAX NUMERIC(10,2),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCTS(CODE),
    CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_CODE) REFERENCES ORDERS(CODE)
);

CREATE TABLE CART (
    CODE SERIAL PRIMARY KEY,
    PRODUCT_CODE INTEGER,
    AMOUNT INTEGER,
    PRICE NUMERIC(10,2),
    TAX NUMERIC(10,2),
    TOTAL NUMERIC(10,2),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCTS(CODE)
);